# Generated by Django 2.1.2 on 2018-12-11 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='today',
            field=models.DateField(default=datetime.datetime(2018, 12, 11, 10, 25, 36, 329567, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
