# Generated by Django 2.1.2 on 2018-12-11 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20181211_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='today',
            field=models.DateField(default=datetime.datetime(2018, 12, 11, 11, 10, 55, 623281, tzinfo=utc)),
        ),
    ]
